[package]
name = "spritecollab-srv"
description = "GraphQL server for interacting with assets and metadata of SpriteCollab."
authors = ["Marco 'Capypara' Köpcke <hello@capypara.de>"]
license = "GPL-3.0-or-later"
version = "0.3.0"
edition = "2021"

[features]
discord = ["serenity", "gethostname"]
discord-reputation = ["hyper-tls"]
activity = ["sc-activity-rec"]

[workspace]
members = [
    "sc-common",
    "sc-activity-rec",
    "spritecollab-pub"
]

[workspace.dependencies]
thiserror = "1.0"
git2 = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.5"
regex = "1.5"
once_cell = "1.12"
anyhow = "1.0"
csv = "1.1"
serde-xml-rs = "0.6"
tokio = { version = "1.18", features = ["full"] }
itertools = "0.11"
chrono = { version = "0.4", features = ["serde"] }

[dependencies]
log = { workspace = true }
pretty_env_logger = { workspace = true }
dotenv = "0.15"
git2 = { workspace = true }
juniper = "0.15"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = { version = "0.5", optional = true }
juniper_hyper = "0.8"
tokio = { workspace = true }
route-recognizer = "0.3"
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-xml-rs = { workspace = true }
csv = { workspace = true }
fred = { version = "6.3", default-features = false }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }
ellipse = "0.2"
backtrace = "0.3"
async-trait = "0.1"
zip = { version = "0.6", features = ["deflate"] }
image = "0.24"
indexmap = "1.8"
gethostname = { version = "0.4", optional = true }
serenity = { version = "0.11", optional = true, default-features = false, features = [
    "builder",
    "cache",
    "chrono",
    "client",
    "gateway",
    "model",
    "http",
    "rustls_backend",
    "utils",
] }
sc-common = { path = "sc-common" }
sc-activity-rec = { path = "sc-activity-rec", optional = true }
