version: '3.3'
services:
  spritecollab:
    image: spritecollab-srv
    build: .
    env_file:
      - .env
    volumes:
      - ./workdir:/workdir
    user: 1000:1000
    ports:
        - "31114:3000"
    stop_grace_period: 10s
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:7
    command:
      - --maxmemory
      - 250mb
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - ""
      - --appendonly
      - "no"
